name: Benchmark
on:
  push: {}
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

jobs:
  build-with-docker:
    name: Build with Docker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Determine upstream commit SHA
        id: upstream
        run: echo "sha=$(cd upstream && git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - uses: docker/setup-buildx-action@v2
      - uses: docker/setup-qemu-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: https://github.com/PostHog/posthog.git#${{ steps.upstream.outputs.sha }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_CONTEXT_KEEP_GIT_DIR=1

  build-with-depot:
    name: Build with Depot
    runs-on: depot-ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Determine upstream commit SHA
        id: upstream
        run: echo "sha=$(cd upstream && git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - uses: depot/setup-action@v1
      - uses: depot/build-push-action@v1
        with:
          context: https://github.com/PostHog/posthog.git#${{ steps.upstream.outputs.sha }}
          platforms: linux/amd64,linux/arm64
          project: tgh7615cwk
          build-args: |
            BUILDKIT_CONTEXT_KEEP_GIT_DIR=1
