name: Benchmark
on:
  push: {}
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

jobs:
  build-with-docker:
    name: Build with Docker
    runs-on: ubuntu-22.04-4
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: docker/setup-buildx-action@v2
      - uses: docker/setup-qemu-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: ./upstream
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_CONTEXT_KEEP_GIT_DIR=1

  build-with-depot:
    name: Build with Depot
    runs-on: depot-ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: depot/setup-action@v1
      - uses: depot/build-push-action@v1
        with:
          context: ./upstream
          platforms: linux/amd64,linux/arm64
          project: j9n4kdn8jn
          build-args: |
            BUILDKIT_CONTEXT_KEEP_GIT_DIR=1
